### ISSUE TITLE
Allow errors to be thrown and not caught

### ISSUE THREAD

**Issue by gingermusketeer** [pillarjs/router#10]
I am using this for mocking external services and it would be awesome to be able to throw errors (failed expectations) and have the router not catch them. Would you be open to a PR allowing this to be configured?

**Comment by gingermusketeer** [comment]
I am wondering if it would be better to have a fork of this repo that is called something like test-router. It would be the same code base but the try catch around the route handler would be removed.

I would prefer not to use the process.nextTick to try and keep the tests as clean as possible

**Comment by dougwilson** [comment]
That's fine. But yea, the change you're asking for is very unlikely to ever happen, because it doesn't make sense.

It's hard to guide you in the right direction for writing tests besides saying to look at all the tests in this module and many other modules under `expressjs`, none of which need to throw uncaught exceptions within route handlers to function. Just from the only example I have to work with above, it seems like you can rewrite it as follows:
```js
// Test setup
var router = new Router()
router.use(bodyParser.json())
var peopleHandler = function(req, res){
  peopleHandler.called = true
  peopleHandler.body = req.body
  res.end()
}
router.post("/people", peopleHandler)

process.env.EXTERNAL_SERVICE_HOST = startServer(router)

// Test
request.post("my-app-under.test/people")
  .send({name: "bob", email: "bob@example.com"})

// After test
expect(peopleHandler.called).to.be.true
expect(peopleHandler.body.name).to.eql("Bob")
expect(peopleHandler.body.email).to.eql("bob@example.com")
```
