### ISSUE TITLE
fast_star not working now but was working with express 4. why it is removed

### ISSUE THREAD

**Issue by aelmardhi** [pillarjs/router#104]
in the express/x4 the [layer.js in express.js](https://github.com/expressjs/express/blob/ea537d907d61dc693587fd41aab024e9df2e14b1/lib/router/layer.js#L48). while in the [initial commet](https://github.com/pillarjs/router/blob/80a9404efe6b6310e5bc35354ec92e5caeeb5207/lib/layer.js#L42) of this repo it does not implemet it. the commit message states that its imported from _express 4_ .and it sayed [there](https://github.com/pillarjs/router/releases/tag/v1.0.0-beta.1) its altered from express 4 but does not show how . 
this is a breaking change which means routes with '*' would not match globally and  white-listed “global” functionality would not work.
if this is a drped feature to use `fast-slash` only, its not reflected in the docs [see](https://expressjs.com/en/5x/api.html:~white-listed%20%E2%80%9Cglobal%E2%80%9D%20functionality.~:)

**Comment by dougwilson** [comment]
Hello, and sorry about that. This is not an exsct drop in for the Express 4 router, which is why Express 4 foes not use this module. This change was intentional.

This repo does not have a goal to document the differences between it and express. The docs on this repo are just meant to explain how this module (which is ultimately unrelated to express and does not require express to use, nor is it part of the expressjs github org) works.

I hope that helps. The history is just explaining where the initial code came from is all, not that it is 100% compatible.

**Comment by dougwilson** [comment]
Also fast_star was added in the express 4 router in 2017, while this module was forked from express 4 in 2014, so that is another reason that you don't see fast_star included in the initial commit of this module: it didn't exist until years later.

**Comment by dougwilson** [comment]
Finally if you are finding any issues in the docs on expressjs.org, you will want to file an issue on the docs issue tracker for the folks there 👍 . The 5x docs in particular are very incomplete.

**Comment by dougwilson** [comment]
It looks like though @HarshithaKP got this change listed in the 5.x migration guide

https://expressjs.com/en/guide/migrating-5.html#path-syntax

> Special * path segment behavior removed

The examples in the actual API docs need to be updated to use the new syntax. Opening an issue (or perhaps even a PR to make the changes) on the expressjs.org repo would be the best course of action 👍

**Comment by aelmardhi** [comment]
that was helpful. thank you for clearing that out. and I will try to do so.
