### ISSUE TITLE
res.send and res.json not available when using router without express?

### ISSUE THREAD

**Issue by sjanuary** [pillarjs/router#39]
I've been working on an example for the docs for #36 but the following didn't work for me:

```javascript
var finalhandler = require('finalhandler')
var http         = require('http')
var Router       = require('router')

var router = Router()
router.get('/', function (req, res) {
  res.setHeader('Content-Type', 'text/plain; charset=utf-8')
  res.json({link: '/abc'})
  res.end()
})

var server = http.createServer(function(req, res) {
  router(req, res, finalhandler(req, res))
})

server.listen(3000)
```

Instead I got `TypeError: undefined is not a function`

It seems like `res.json` and `res.send` aren't available if a Router is used standalone without Express. Is this by design? I couldn't find anything about it in the docs or in past issues.

**Comment by dougwilson** [comment]
This is by design, as those are not part of routing a request. The router just routes requests to handles. Anything the router provides should be in the README in the repository (and it doesn't call out to everything not included, as that would be a pretty much endless list--if it's not in the docs, it can be assumed to not exist).

With the router, your `req` and `res` will simply look like however they looked when you passed them into the main `router` function. In your example, you are passing what comes from `http.createServer`, so the methods on those objects are documented in node.js:

https://nodejs.org/api/http.html

**Comment by sjanuary** [comment]
Thanks @dougwilson, that makes sense.
