### ISSUE TITLE
On posts, always 405 Method Not Allowed error

### ISSUE THREAD

**Issue by binarykitchen** [pillarjs/router#40]
```
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Length: 167
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 167 out of 167 bytes
< HTTP/1.1 405 Method Not Allowed
< Allow: GET, HEAD, OPTIONS
< Content-Length: 0
< Date: Sun, 13 Mar 2016 02:46:59 GMT
< Connection: keep-alive
```

Why doesn't it take POST requests anymore? I have `router.use(bodyParser.json())` and a `router.post('/contact', function(req, res) { ... })` handler.

**Comment by dougwilson** [comment]
Hi @binarykitchen, you have something else going on, because this module has no code to send back a 405 status code, so that response is coming from something outside of this module.

Perhaps if you provided all the code necessary for me to reproduce the issue, I could figure out what is sending back the 405 in your code.

**Comment by binarykitchen** [comment]
It is this code:
https://github.com/binarykitchen/videomail-client/blob/master/Gulpfile.js#L104

The Post on `/contact` never occurs. Weird. It worked few months ago.

**Comment by dougwilson** [comment]
Hi @binarykitchen, like I said, there is no code in this module to send any 405 status code, so I'm not sure where it would be coming from. The code you linked to is enormous, and it looks like there are steps to get it running you didn't outline. Can you attach a debugger to your script and set a break point when `res.end` is called or something? Then you can probably find out where the 405 is actually coming from.

**Comment by binarykitchen** [comment]
thanks man. but i do not see what you suggest with `res.end`? where and what would you put it?

**Comment by dougwilson** [comment]
Hey @binarykitchen, what debugger are you using? I'm talking about `res.end`, a part of the built-in Node.js HTTP server. Many debuggers you can set a break point in the code, so you would just browse into the code Node.js `http` module and set a break point on the `OutgoingMessage.prototype.end` method and then hit that endpoint to see what the stack look like and browse up the stack to see what is sending the 405.

How to use debuggers and stuff is likely outside the scope of this issue board, which is just about issues with this module (and the module has no code at all to send back a 405). You may want to ask on a chat forum to get some interactive help with debugging your Node.js application.

**Comment by binarykitchen** [comment]
@dougwilson that would be a solution but never tried before. but i have nodejs installed via apt-get and do not have access to its source code. so, can't add breakpoints.

isn't there an easier way to investigate this oddness? why are POSTs not allowed?

**Comment by dougwilson** [comment]
Hi @binarykitchen, I'm not sure. I took the code you pointed me to, which uses the `router`, run it by itself, and the POST worked just fine. The issue is, you are returning the `router` variable in an array to some really big system, which I have no idea what it is doing. On top of that, this module has no code at all to send back a 405, so I have no idea where it could be coming from, but there is nothing wrong with your code using `router` and trying to receive a POST, as you can see if you run that code by itself, without all that gulp stuff going on.

**Comment by binarykitchen** [comment]
that's good to know. many thanks man.

i think i found the culprit. it is an nginx issue ... figuring out now how to allow POSTs in nginx ...

**Comment by dhananjaychoudhari** [comment]
why show  the 405 not allowed  in my PHP project?
