### ISSUE TITLE
Allow for identifying 404 vs. 405

### ISSUE THREAD

**Issue by whitlockjc** [pillarjs/router#62]
Whenever `router` fails to match a request, it can be one of two reasons:

1. Method mismatch _(`405`)_
2. Path mismatch _(`404`)_

I cannot seem to figure out a way to differentiate between the two in my `finalhandler` and I was hoping that either someone can point me in the right direction or maybe `router` can be updated to allow for such things.

**Comment by wesleytodd** [comment]
AFAIK the router package does not support this.  Looking through the code I think it would drastically change the way things are done to be able to support it.  Right now, if the method does not match, then it actually skips the whole path matching.  This is a perf improvement because the path matching is the least efficient part.

I *think* (although have not tried) that you could rig up your routes in such a way as you can do this manually, like:

```javascript
router.route('/foo')
  .get(getHandler)
  .post(postHandler)
  .all(function (req, res) {
    res.status(405);
  })
;
```

But you would have to be careful that nothing else after was supposed to handle the route.

**Comment by whitlockjc** [comment]
Why does it have to be a drastic change?  Looking [at the source](https://github.com/pillarjs/router/blob/master/lib/route.js#L138), it seems very simple.  You could add a property to `err` based on whether the miss was due to method and/or path and let the `finalhandler` use this property to return a `404` or a `405`.  In fact, I'll submit a PR for this.

**Comment by whitlockjc** [comment]
I am aware now that this would be a breaking change and that isn't ideal.  And since the test suite relies heavily on the current support...this could be bigger than expected.  But the logic for this seems pretty simple.

**Comment by wesleytodd** [comment]
I didn't mean the code change was drastic, rather that the effect of the change would be.  Since it is quick I don't see a reason not to submit a PR, but I am not sure I am in support of testing route matching when the method does not match.

**Comment by whitlockjc** [comment]
I thought about wrapping this up in a configuration option but after implementing this, there is no way to make it work.  For a method/path miss, there is no `err` sent to the `done` callback right now.  I _could_ add one for this but that would change the current handling so using a configuration option alone isn't enough.  I am not sure sending an `err` downstream is such a bad idea but it is a deviation from the current functionality and my concern would be breaking backward compatibility.

I'll leave this open for now but if you think it's not worth considering further, I'm cool if you close it.  I do think it's a good idea to be able to differentiate between `404` and `405`.

**Comment by wesleytodd** [comment]
> I do think it's a good idea to be able to differentiate between 404 and 405

On this I agree completely.

Sending an `err` when a route misses is not something we can ever do, because it is *not* an error, as it could just be handled further down the route stack.  There have been a few discussions around tracking the matched layers, which might enable this handling in a more generic way.  See #34 & #56.  Both of which might enable you to build this feature as a third party.  Also there is still the option I listed above using the `route` and `.all` methods.

**Comment by whitlockjc** [comment]
I'll give the `.all` option you suggested earlier a try and if it works, we can maybe get the docs updated to suggest doing this?

**Comment by wesleytodd** [comment]
LMK if #62 works for you.

**Comment by whitlockjc** [comment]
Yep, it worked great!  Thanks a ton.
