### ISSUE TITLE
Http/2 support?

### ISSUE THREAD

**Issue by lukasoppermann** [pillarjs/router#77]
Hey, 

I am sorry if I missed it, but I could not find it in the readme or in any issue:
Does this router support node's http/2 server?

Thanks.

**Comment by lukasoppermann** [comment]
Thanks @dougwilson one more question, so the express 5 alpha uses router@2, correct? So does this express alpha already support http/2 as well?

**Comment by dougwilson** [comment]
I will add to readme, sorry didn't mean to close the issue. It's basically take the example https://github.com/pillarjs/router/blob/master/README.md#api and replace http with http2. You'll probably need to refer to Node.js docs to configure SSL for the http2 server.

**Comment by dougwilson** [comment]
This is a different project. Express 5 alpha does not support http2. If you're looking to use it there, you can open an issue or look through the existing http2 issues on the express issue tracker.

**Comment by lukasoppermann** [comment]
Thank you for the clarification. I appreciate you taking the time! 

Sorry for the confusion, I assumed that in the release notes for express where they refer to `deps: router@2.0.0-alpha.1` (https://github.com/expressjs/express/releases/tag/5.0.0-alpha.7) this package was meant.

**Comment by dougwilson** [comment]
Yes, that is referring to this project. But just because it uses some module doesn't imply the support. Express.js is doing more than simply importing the router; it adds all the sugar methods like res.send and etc that would need to work with http2 in order for Express.js as a whole to woth with http2.

That is really the wrong forum to talk about express, though, as this issue tracker is a different project. It would be lile discussion express on the node issue tracker just because it uses node :)
